### PR TITLE
General: Codestyle fixes to comply with PSR-12

### LINKED ISSUE #8: chore: Follow PSR-12 codestyle
To make it easier to contribute and even understand the code we should follow a nicer codestyle than the current one.

Within the M2mobi team we decided on PSR-12.

### PR DESCRIPTION
**Pull request by Martijnsvb**
Fixes #8

### CODE REVIEW

**Comment by SMillerDev** [comment]
You'll have to rebase on master now.

File: ApnsPHP/Feedback.php [hunk 1]
```diff
@@ -18,7 +19,7 @@
  */
 
 /**
- * @defgroup ApnsPHP_Feedback Feedback
+ * @defgroup Feedback Feedback
```
Comment (SMillerDev) [inline ApnsPHP/Feedback.php:22]: These tags aren't really needed anymore

File: ApnsPHP/Feedback.php [hunk 2]
```diff
@@ -35,85 +36,91 @@
  * on the identified devices, a provider should stop sending notifications to these
  * devices.
  *
- * @ingroup ApnsPHP_Feedback
+ * @ingroup Feedback
```
Comment (SMillerDev) [inline ApnsPHP/Feedback.php:39]: These tags aren't really needed anymore

**Comment by SMillerDev** [comment]
And you'll have to rebase again for CI to pass. As part of this review, can you disable `continue-on-error` in the github workflow for PHPCS? Since it should be failing otherwise.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @Martijnsvb !
